// Code generated by "stringer -type=Status"; DO NOT EDIT.

package patient

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Грипп-0]
	_ = x[Зомби_вирус-1]
	_ = x[Простуда-2]
}

const _Status_name = "ГриппЗомби_вирусПростуда"

var _Status_index = [...]uint8{0, 10, 31, 47}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}
